osx_image: xcode9.3
language: objective-c

before_install:
  - gem install xcpretty

script:
  - xcodebuild test -scheme Karte -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3' | xcpretty
  - pod lib lint

after_success:
  # - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
