osx_image: xcode8.3
language: objective-c

before_install:
  - gem install xcpretty

script:
  - xcodebuild -scheme Karte | xcpretty
  # - xcodebuild test -scheme Karte -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' | xcpretty
  # - pod lib lint

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
